development:
  user: fedoraAdmin
  password: fedoraAdmin
  url: http://10.250.109.55:8080/fedora
#test:
#  user: fedoraAdmin
#  password: fedoraAdmin
#  url: http://localhost:8983/fedora3
#production:
#  user: fedoraAdmin
#  password: fedoraAdmin
#  url: http://localhost:8983/fedora3